--CREATE TABLE [dbo].[Table]
--(
--	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
--    [fname] NVARCHAR(20) NOT NULL, 
--    [lname] NVARCHAR(20) NOT NULL, 
--    [city] NVARCHAR(50) NULL,
--    [date] DATE NOT NULL,
--    [email] NVARCHAR(50) NOT NULL,
--    [username] NVARCHAR(50) NOT NULL,
--    [password] NVARCHAR(12) NOT NULL,
--    [phone] NVARCHAR(11) NOT NULL,
--    [gender] NVARCHAR(6) NOT NULL,
--    [question1] NVARCHAR(50) NULL,
--    [answer1] NVARCHAR(50) NULL,
--    [question2] NVARCHAR(50) NULL,
--    [answer2] NVARCHAR(50) NULL
--)
select * from [Table]